# Generated by Django 3.2 on 2021-05-14 12:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('MBP', 'MacBook Pro'), ('MBA', 'MacBook Air'), ('iMAC', 'iMac'), ('iMACPRO', 'iMac Pro'), ('MINI', 'Mac Mini'), ('MACPRO', 'Mac Pro')], default='MBP', max_length=10)),
                ('title', models.CharField(max_length=250)),
                ('description', models.TextField()),
                ('year', models.CharField(max_length=4)),
                ('color', models.CharField(max_length=10)),
                ('storage', models.CharField(max_length=10)),
                ('ram', models.CharField(max_length=10)),
                ('screen', models.CharField(max_length=10)),
                ('image', models.ImageField(upload_to='product/images/')),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('active', models.BooleanField(default=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-last_updated'],
            },
        ),
        migrations.CreateModel(
            name='Reseller',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('url', models.CharField(max_length=250)),
                ('active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProductsByReseller',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.product')),
                ('reseller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.reseller')),
            ],
        ),
    ]
