# Generated by Django 3.2 on 2021-05-14 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='productsbyreseller',
            name='price',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='reseller',
            name='url',
            field=models.URLField(max_length=250),
        ),
    ]
