# Generated by Django 3.2 on 2021-05-14 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_auto_20210514_1243'),
    ]

    operations = [
        migrations.AddField(
            model_name='reseller',
            name='email',
            field=models.EmailField(default='', max_length=250),
        ),
        migrations.AddField(
            model_name='reseller',
            name='phone',
            field=models.CharField(default='', max_length=50),
        ),
    ]
