# Generated by Django 3.2 on 2021-05-16 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0009_item_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reseller',
            name='email',
            field=models.EmailField(blank=True, default='', max_length=250),
        ),
        migrations.AlterField(
            model_name='reseller',
            name='phone',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
    ]
