# Generated by Django 3.2 on 2021-05-22 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0010_auto_20210516_0250'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='url',
            field=models.URLField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, upload_to='product/images/'),
        ),
        migrations.AlterField(
            model_name='product',
            name='ram',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='product',
            name='type',
            field=models.CharField(choices=[('MBP', 'MacBook Pro'), ('MBA', 'MacBook Air'), ('iMAC', 'iMac'), ('iMACPRO', 'iMac Pro'), ('MINI', 'Mac Mini'), ('MACPRO', 'Mac Pro'), ('iPHONE', 'iPhone'), ('iPAO', 'iPad'), ('WATCH', 'watch')], default='MBP', max_length=10),
        ),
    ]
