# Generated by Django 3.2 on 2021-08-29 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0013_article'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='product',
            field=models.CharField(blank=True, choices=[('MBP', 'MacBook Pro'), ('MBA', 'MacBook Air'), ('iMAC', 'iMac'), ('iMACPRO', 'iMac Pro'), ('MINI', 'Mac Mini'), ('MACPRO', 'Mac Pro'), ('iPHONE', 'iPhone'), ('iPADPRO', 'iPad Pro'), ('iPADAIR', 'iPad Air'), ('iPADMINI', 'iPad Mini'), ('iPAD', 'iPad'), ('WATCH', 'watch')], default='MBP', max_length=10, null=True),
        ),
    ]
