# Generated by Django 3.2 on 2021-08-29 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0019_alter_article_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='source_url',
            field=models.URLField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
