# Generated by Django 3.2.10 on 2021-12-24 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0020_article_source_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='reseller',
            name='slug',
            field=models.SlugField(blank=True, null=True),
        ),
    ]
