# Generated by Django 3.2.10 on 2021-12-24 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0022_alter_reseller_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='reseller',
            name='logo',
            field=models.ImageField(blank=True, upload_to='reseller/images/'),
        ),
    ]
