# Generated by Django 3.2.12 on 2022-02-20 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0023_reseller_logo'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceCenters',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('url', models.URLField(max_length=250)),
                ('email', models.EmailField(blank=True, default='', max_length=250)),
                ('phone', models.CharField(blank=True, default='', max_length=50)),
                ('active', models.BooleanField(default=True)),
                ('slug', models.SlugField()),
            ],
        ),
        migrations.AlterField(
            model_name='reseller',
            name='logo',
            field=models.ImageField(blank=True, upload_to='reseller/'),
        ),
    ]
