# Generated by Django 3.2.12 on 2022-02-20 13:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0024_auto_20220220_1343'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ServiceCenters',
            new_name='ServiceCenter',
        ),
    ]
